# Generated by Django 4.2.1 on 2023-05-13 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
