# Generated by Django 4.2.1 on 2023-05-28 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import monapplication.models


class Migration(migrations.Migration):

    dependencies = [
        ('monapplication', '0003_alter_utilisateur_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomanimal', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('race', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=monapplication.models.filepath)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
